site_name: Envi OData Public API 1.0
nav:
    - Introduction: Introduction.md
    - Testing with Postman: Testing with Postman.md 
    - Inventory: Inventory.md
    - Addresses: Addresses.md
theme: 
    name: material
    logo: assets/logo.png
    favicon: img/favicon.png
    palette:
      primary: black
    features:
      - content.code.annotate

markdown_extensions:
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

use_directory_urls: false